# docker-compose.yml
version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8765:80"
    container_name: multi_blanco
    expose:
      - "80"
    # volumes:
    # - /Users/kbs/git/peladonerd/varios/1/www:/usr/share/nginx/html:ro
    # - //d/storeDocker/html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=multiblanco.apps.com.pe,www.multiblanco.apps.com.pe
      - LETSENCRYPT_HOST=multiblanco.apps.com.pe,www.multiblanco.apps.com.pe
      - LETSENCRYPT_EMAIL=miguekos1233@gmail.com
networks:
  default:
    external:
      name: nginx-proxy_default
